### ISSUE TITLE
Usage example with scala-logging 

### ISSUE THREAD

**Issue by nemccarthy** [portingle/slf4jtesting#1]
Hey guys,

We are big users of scala-logging, wondering if you had an example of using this with it/. 

Cheers

**Comment by Johnlon** [comment]
I use this test library with the Typesafe logging wrapper.

The key with Scala, as with Java, is to inject the logging factory interface rather than using the static     LoggerFactory.getLogger nonsense.

So you'd have something like this with Typesafe logging (I've not compiled it)....

```
class MyService(loggerFactory: ILoggerFactory) {
  private val logger = com.typesafe.scalalogging.Logger(loggerFactory.getLogger(classOf[MyService].getName))

  logger.info(....)
}
```

Hope that makes sense?

**Comment by Johnlon** [comment]
Added this to the readme - thanks again
