### ISSUE TITLE
Expose LogMessage for more flexibility in writing assertions

### ISSUE THREAD

**Issue by bencody** [portingle/slf4jtesting#4]
Hi,

slf4jtest.LoggerExtensions#matches is quite restrictive as it only enables assert true/false assertions to be written. slf4jtest.LoggerExtensions#lines could be more useful as one could write AssertJ or Hamcrest asserts against the LogMessage results, which can output more expressive failure messages, rather than something along the lines of "expected true, was false".

Unfortunately, LogMessage is package-private. Could you please make it public?

Thanks,

Ben

**Comment by Johnlon** [comment]
Incredible timing
 I came across the same irritations yesterday and was fixing them tonight, meant to do it yesterday but helping the kids with homework got in the way.
The package private was a plain accident but yes it prevents more flexible matching including using a Functional style.
Also i was planning to add a matches(Pattern) so that one can choose how the matcher works, eg Pattern.DOTALL.
Are you using scala or Java btw?

**Comment by Johnlon** [comment]
Hopefully release 1.1.1 covers your concerns.
Please verify this is what you are looking for.
RSVP thanks

**Comment by bencody** [comment]
I'm using Java.

**Comment by Johnlon** [comment]
Release 1.1.1 done
